# Generated by Django 5.2 on 2025-12-09 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Member_Portal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=50)),
                ("last_name", models.CharField(max_length=50)),
                ("member_id", models.CharField(max_length=50, unique=True)),
                ("expiry_date", models.CharField(max_length=50)),
                ("status", models.CharField(max_length=50)),
                ("location", models.CharField(max_length=50)),
                ("membership", models.CharField(max_length=50)),
                ("age", models.IntegerField()),
                ("service", models.CharField(max_length=50)),
                ("gender", models.CharField(max_length=50)),
                ("join_date", models.DateField(auto_now_add=True)),
            ],
            options={
                "db_table": "member_portal_tb",
                "indexes": [
                    models.Index(
                        fields=["first_name"], name="member_port_first_n_dc7a9f_idx"
                    ),
                    models.Index(
                        fields=["last_name"], name="member_port_last_na_fbc0f4_idx"
                    ),
                    models.Index(
                        fields=["member_id"], name="member_port_member__69430b_idx"
                    ),
                    models.Index(
                        fields=["expiry_date"], name="member_port_expiry__58f275_idx"
                    ),
                    models.Index(
                        fields=["status"], name="member_port_status_704045_idx"
                    ),
                    models.Index(
                        fields=["location"], name="member_port_locatio_768b5d_idx"
                    ),
                    models.Index(
                        fields=["membership"], name="member_port_members_204e37_idx"
                    ),
                    models.Index(fields=["age"], name="member_port_age_a21b13_idx"),
                    models.Index(
                        fields=["service"], name="member_port_service_b2a27c_idx"
                    ),
                    models.Index(
                        fields=["gender"], name="member_port_gender_8b19f3_idx"
                    ),
                    models.Index(
                        fields=["join_date"], name="member_port_join_da_da9d48_idx"
                    ),
                ],
            },
        ),
    ]
