# Generated by Django 5.2 on 2026-01-14 00:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Member_Portal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=50)),
                ("last_name", models.CharField(max_length=50)),
                ("member_id", models.CharField(max_length=50, unique=True)),
                ("phone_number", models.CharField(max_length=50)),
                ("email", models.CharField(max_length=50)),
                ("avail", models.CharField(max_length=50)),
                ("expiry_date", models.DateField()),
                ("status", models.CharField(max_length=50)),
                ("location", models.CharField(max_length=50)),
                ("membership", models.CharField(max_length=50)),
                ("monthly_fee", models.IntegerField()),
                ("age", models.IntegerField()),
                ("service", models.CharField(max_length=50)),
                ("gender", models.CharField(max_length=50)),
                ("paid", models.BooleanField(default=False)),
                ("image", models.ImageField(upload_to="member_images")),
                ("join_date", models.DateField(auto_now_add=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "member_portal_tb",
                "indexes": [
                    models.Index(
                        fields=["first_name"], name="member_port_first_n_dc7a9f_idx"
                    ),
                    models.Index(
                        fields=["last_name"], name="member_port_last_na_fbc0f4_idx"
                    ),
                    models.Index(
                        fields=["member_id"], name="member_port_member__69430b_idx"
                    ),
                    models.Index(
                        fields=["expiry_date"], name="member_port_expiry__58f275_idx"
                    ),
                    models.Index(
                        fields=["status"], name="member_port_status_704045_idx"
                    ),
                    models.Index(
                        fields=["location"], name="member_port_locatio_768b5d_idx"
                    ),
                    models.Index(
                        fields=["membership"], name="member_port_members_204e37_idx"
                    ),
                    models.Index(fields=["age"], name="member_port_age_a21b13_idx"),
                    models.Index(
                        fields=["service"], name="member_port_service_b2a27c_idx"
                    ),
                    models.Index(
                        fields=["gender"], name="member_port_gender_8b19f3_idx"
                    ),
                    models.Index(
                        fields=["join_date"], name="member_port_join_da_da9d48_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="MemberLoginRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("login_time", models.DateTimeField(auto_now_add=True)),
                ("logout_time", models.DateTimeField(blank=True, null=True)),
                ("duration", models.DurationField(blank=True, null=True)),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="member_portal.member_portal",
                    ),
                ),
            ],
            options={
                "db_table": "login_record",
            },
        ),
    ]
