# Generated by Django 5.2 on 2025-12-09 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("member_portal", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="member_portal",
            name="avail",
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="member_portal",
            name="email",
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="member_portal",
            name="image",
            field=models.ImageField(default=1, upload_to="member_images"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="member_portal",
            name="monthly_fee",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="member_portal",
            name="paid",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="member_portal",
            name="phone_number",
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
