# Generated by Django 5.2 on 2026-01-25 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pos_portal", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cartitem",
            name="image",
        ),
        migrations.AddField(
            model_name="transaction",
            name="cashAmount",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
