# Generated by Django 5.2 on 2026-01-25 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pos_portal", "0002_remove_cartitem_image_transaction_cashamount"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="transaction_id",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
